### ISSUE TITLE
1000—Phase 0 spec freeze

### ISSUE THREAD

**Issue by protolambda** [ethereum/eth2.0-specs#1000]
№ 1000 :tada: Congratz everyone!

This issue will track the progress towards phase 0 spec-freeze, a big milestone towards launch of phase 0.

------

# The Phase 0 spec freeze

The idea of the spec-freeze is to enable client implementers to settle on a stable version of the spec, and prepare for launch. It is crucial to scrutinize the spec before this freeze, and find & fix any remaining bugs.

## To be frozen for Phase 0:

- `core/`
  - `0_beacon-chain.md`
  - `0_deposit-contract.md`
  - `0_fork-choice.md`
- `validator/`
  - `0_beacon-chain-validator.md`
- `networking`
  - TBD

## Timeline

- April 9 - Sydney workshop
- April 18 - [Impl call \#16](https://github.com/ethereum/eth2.0-pm/issues/37)
- April 24 - [Release v0.6.0](https://github.com/ethereum/eth2.0-specs/releases/tag/v0.6.0)
- May 2 - [Impl call \#17](https://github.com/ethereum/eth2.0-pm/issues/42)
- May 4 - [Release v0.6.1](https://github.com/ethereum/eth2.0-specs/releases/tag/v0.6.1)
- May 6-12: generalized test case setup: complete state-transition tests.
- May 13-15: Many in NY, prepare workshop
- May 16 - [New York workshop, hosted by Pegasys](https://www.eventbrite.com/e/road-to-interop-tickets-60384211803): focus on client interop.
- May 17-19: EthNY hackathon, opportunity to implement new workshop ideas
- May 20 - May 31: more v0.6.x work
- June 1: possible date for v0.7.0 (if we do one)
- June 1-30: finalize things & make sure spec is ready to freeze
- **June 30: FREEZE** (as per [this tweet](https://twitter.com/CarlBeek/status/1115829938668617728?s=20))
- July 1 and later: implement frozen spec, testnets, etc. Launch target date TBD.

## Action points for freeze

- Testing:
  - [x] complete state-transition tests
    - [x] unify "case setup" part of pytests and state-transition yaml-tests. (It is rather painful to duplicate effort between testing of the spec itself, and generation of test-vectors for clients. We're looking to unify where possible)
      - [x] implement block-operation test cases described in #927
    - [x] generate tests covering larger transitions, similar to chain-tests
    - [x] Higher coverage with state-transition tests. From a client (yaml consuming) view. Spec already has good coverage. (See #1200) Note: rewards/penalties epoch processing tests are postponed. All other tests made it in :tada: 
  - [x] fork-choice test vectors (See #1185)
    - Note; some were implemented. To be extended some time in after freeze.
  - [x] fuzzing
    - [x] differential fuzzing between pyspec and ZRNT
    - [x] fuzz ZRNT, look for panics / broken invariants
  - ~~invariants testing, cc @JustinDrake~~ part of fuzzing
- Experimentation:
  - network spec (if included) needs testing too
  - implement & iterate on pain points, don't wait till after spec freeze.
- Improve & simplify phase 0 spec where possible.
  - ~~TODO: document things to be improved / changed (or added, if any)~~ See #1054
- Standardize constant presets.
  - [x] minimal: constants for fast testing, may not be reliable enough for a testnet.
  - ~~testnet: minimum viable reduced constants for a testnet.~~ Minimal for now, will experiment more during interop testing.
  - [x] mainnet: spec costants

**Comment by JustinDrake** [comment]
I suggest keeping track of [this](https://www.google.com/search?q=days+till+june+30&oq=days+till+&aqs=chrome.1.69i57j69i59j0l4.2616j0j7&sourceid=chrome&ie=UTF-8). We need to find about one bug a day to squash them all before freeze.

**Comment by hwwhww** [comment]
> Tracking issue for first public testnet 

I suggest that could be in https://github.com/ethereum/eth2.0-pm/ repo 😄

**Comment by protolambda** [comment]
Updated issue with spec-freeze tracking suggestion from @JustinDrake

**Comment by JustinDrake** [comment]
Some personal notes to set the right expectations for the spec freeze:

1) The main purpose for a spec freeze is to see the emergence of long-lived cross-client testnets by halting new `master` releases.
2) We reserve the right to do cosmetic changes (i.e., any change that doesn't change `hash_tree_root(state)`) to the phase 0 spec (especially on `dev`) after the freeze.
3) BLS standardisation is unlikely to be finalised by June 30, although significant progress will have been made. Any inconsistency with the final standard will have to be reflected in the final launch release.
4) Bug fixes will obviously have to be incorporated in the final launch release. If the bug impedes the formation of cross-client testnets (e.g. causes the state transition to stall) then an "emergency point release" will likely be warranted. If not, bug fixes can accumulate (unreleased) in the `dev` branch until much closer to launch.
5) Simplifications and cleanups found between July 1 and the actual launch date will likely not warrant making a `master` release. Such simplifications and cleanups will have to be assessed on an ad-hoc basis for incorporation in the final release.

**Comment by protolambda** [comment]
This issue is more or less complete (See #1231 for last tiny testing update). We will be polishing and pushing the last feature PR for freeze now. Closing this to focus on the remaining freeze issues/PR.
