### ISSUE TITLE
Fork choice spec checklist

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#1053]
- [x] 1. **Executable spec**: Make the fork choice spec executable.
- [ ] 2. (*post-freeze discussion*) **Maximum reversions**: Enshrine dynamic weak subjectivity reversion period into fork choice rule ("second finality mechanism").
- [x] 3. **Slashed validators**: Decide whether slashed validators should be ignored or not. (Current inclination is to not ignore slashed validators.)
- [x] 4. **Eth1 validity**: Explicitly require the Eth1 fork pointed to by `state. latest_eth1_data` to be valid and available.
- [x] 5. **Manual forks**: Specify how manual forks are enacted and the corresponding interaction with `state.fork`.
- [x] 6. **Genesis event**: Revisit how the genesis event is defined, especially if `Eth2Genesis` is removed from the deposit contract (see #1048). Formalise the genesis event in the fork choice rule.
- [x] 7. (*post-freeze discussion*) **Flip-flop attack hardening**: Decide if there is anything actionable regarding [flip-flop attacks](https://ethresear.ch/t/beacon-chain-casper-mini-spec/2760/19).
- [x] 8. (*post-freeze discussion*) **Revisit `SECONDS_PER_SLOT`**: Potentially increase to 8 or 12 seconds.
- [x] 9. **Clocking**: Formalise the notion of an "honest clock", e.g. maximum drift from "real" time. Decide if there is anything actionable from [this research post](https://ethresear.ch/t/network-latency-based-clocks-and-their-limits/2053).
- [x] 10. **Tie breakers**: Make sure the fork choice is always well-defined. In particular, check that all ties are broken. For example, "Let `finalized_head` be the finalized block with the highest epoch." is not well-defined if there are two finalized heads with the highest epoch.

**Comment by djrtwo** [comment]
This also needs to be added. In the context of a non-executable spec, it is a one-liner
https://github.com/ethereum/eth2.0-specs/issues/768

**Comment by JustinDrake** [comment]
We also need to be mindful of the DoS where many forks need to be followed through epoch transitions.

**Comment by vbuterin** [comment]
>  10. Tie breakers: Make sure the fork choice is always well-defined. In particular, check that all ties are broken. For example, "Let finalized_head be the finalized block with the highest epoch." is not well-defined if there are two finalized heads with the highest epoch.

FWIW my current code ( https://github.com/ethereum/eth2.0-specs/pull/1068/files#diff-65ff52fa41121e465ff23d3b53fd0518R205 ) de facto makes the winner be "the first finalized head you discovered", ie. it's a memory-ful fork choice rule. And it has to be memory-ful because that's how weak subjectivity works anyway.....

>  7. Flip-flop attack hardening: Decide if there is anything actionable regarding flip-flop attacks.

I have been waiting for Yan to finish a liveness proof to finalize this.

**Comment by djrtwo** [comment]
all items except (2) are addressed. Closing in favor of #1520
