### ISSUE TITLE
Phase 0 state transition checklist—take 5

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#1054]
(See #128, #218, #322, #675 for takes 1, 2, 3, 4.)

This issue keeps track of possible phase 0 state transition function changes.

- [x] 1. (*post-freeze discussion*) **BLS12-381 standardisation**: See [here](https://github.com/pairingwg/bls_standard).
- [x] 2. (*post-freeze discussion*) **Big vs little byteorder of `hash_tree_root` inputs**: See also #556.
- [x] 3. (*post-freeze discussion*) **Performance parameters fine-tuning**: E.g. review `SLOTS_PER_EPOCH` and `SHARD_COUNT` based on benchmarks.
- [x] 4. **Issuance schedule**: Enact schedule whereby `2**21` ETH is issued per year when `2**27` ETH is at stake.
- [x] 5. <s>**Better aligned micro-incentives**: Make crosslink incentives proportional to number of epochs in a crosslink. Make matching head incentives proportional to head slot vs target slot.</s>
- [x] 6. <s>**Stateless withdrawal credentials**: Consider not storing withdrawal credentials. See #937.</s>
- [x] 7. **Remove `MIN_ATTESTATION_INCLUSION_DELAY`**: Set `MIN_ATTESTATION_INCLUSION_DELAY` to `1`.
- [x] 8. (*post-freeze discussion*) **Remove transfers**: Consider completely removing the `Transfer` operation, going beyond `MAX_TRANSFERS = 0`. We want to do a practice hard fork that add a field to an SSZ object (in this case, adding the `transfers` field to `BeaconBlockBody`).
- [x] 9. (*post-freeze discussion*) **Last slot vs first slot epoch transitions**: See #1043.
- [x] 10. <s>**Merged historical stats**: Consider merging `latest_randao_mixes`, `latest_active_index_roots`, `latest_slashed_balances` into a single SSZ object.</s>
- [x] 11. **More historical stats**: Store the last 8 months of historical lists so that historical start shards can be recomputed.
- [x] 12. **Crosslink lengths**: Fix #1034.
- [x] 13. **Bitfields/bigints/generalised indices**: See #1019.
- [x] 14 **Fine-tune object field ordering**: See #917.
- [x] 15 **`Crosslink` in `AttestationData`**: See #1044.
- [ ] 16 (*post-freeze discussion*) **Exit fee**: See https://github.com/ethereum/eth2.0-specs/pull/850#issuecomment-478068655.
- [x] 17 **Improve upon `latest_active_index_roots`**: For more efficient light clients. See #1104
- [x] 18 (*post-freeze discussion*) **Hard Forkability**: See #1101, also related to **8**
- [x] 19 **Fixed size state**: Make `BeaconState` fixed size to be friendly to SSZ partials.
- [x] 20 **Checkpoints**: Refactor `BeaconState` to use `Checkpoint`s.
- [x] 21 **Slashing early exit**: (bug) In some circumstances getting slashed allows for an early exit.

**Comment by vbuterin** [comment]
>  2. Big-endian vs little-endian hash_tree_root: See #556.

What are the places where little endian is still used in the hash tree root?

I have a strong preference toward not, for example, reversing the bytes of hashes the way bitcoin does. I had to deal with that as an implementer and it was painful. Endianness should be purely a convention about how we serialize things that are integers within the eth2 spec; we should be treating everything outside the eth2 spec proper (eg. hash algorithms, BLS signature and BLS pubkey serialization...) as black boxes that just give us `bytes`.

**Comment by JustinDrake** [comment]
> What are the places where little endian is still used in the hash tree root?

To only place is `byteorder` when calling `to_bytes` on a `uintN` for `N in [16, 32, 64, 128, 256]`. This affects, for example, `hash_tree_root` of a slot number (of type `uint64`).

It's confusing that "endianness" is used for both bits and bytes. What about using big/little "byteorder" and "bitorder" instead?

> we should be treating everything outside the eth2 spec proper (eg. hash algorithms, BLS signature and BLS pubkey serialization...) as black boxes that just give us bytes

Agreed :)

**Comment by vbuterin** [comment]
Ah sorry, meant to ask where big endian is used in tree hash root. To me it seems obvious that if SSZ serialization uses little endian then so should SSZ tree hashing, so I don't see the issue....

Bitorder is only relevant for bitfields, correct?

**Comment by vbuterin** [comment]
>  5. Better aligned micro-incentives: Make crosslink incentives proportional to number of epochs in a crosslink. Make matching head incentives proportional to head slot vs target slot.

This is arguably a bad idea, because the total payment that validators get would potentially be larger (!!!) if they skip crosslinks. That is:

* Honest strategy: `(100% vote) (100% vote) (100% vote) (100% vote)`
* Honest reward: `1 + 1 + 1 + 1 = 4`
* Evil strategy: `(60% vote) (60% vote) (60% vote) (100% vote)`
* Evil reward: `0.6**2 + 0.6**2 + 0.6**2 + (1 * 4) = 5.08` (or if we're even stupider with the implementation: `0.6**2 + (0.6**2 * 2) + (0.6**2 * 3) + (1 * 4) = 6.16`)

**Comment by vbuterin** [comment]
>  16 Exit fee: See #850 (comment).

Do we want an exit fee or a minimum time online? We already have this:

```
    # Verify the validator has been active long enough
    assert get_current_epoch(state) >= validator.activation_epoch + PERSISTENT_COMMITTEE_PERIOD
```

**Comment by djrtwo** [comment]
> Consider completely removing the Transfer operation, going beyond MAX_TRANSFERS = 0. We want to do a practice hard fork that add a field to an SSZ object (in this case, adding the transfers field to BeaconBlockBody).

I'm not seeing much value here especially considering clients already have this functionality built and tested. If we sequester Transfer to another fork in between 0 and 1, we would have to define a whole state transition file for the in between fork. Coordinating a production fork around a constant change is significant enough IMO

**Comment by djrtwo** [comment]
> Last slot vs first slot epoch transitions

Down to get on a call to convince you that this is still not the proper path  :)

**Comment by djrtwo** [comment]
All items except (16) have been addressed. Closing this in favor of specific issue on exit fee #1521
