### ISSUE TITLE
Deposit contract checklist

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#1129]
- [x] 1. **Unify repos**: Move deposit contract to `eth2.0-specs` repo. See #1127.
- [x] 2. **Remove `Eth2Genesis`**: Rely on a more flexible genesis trigger, external to deposit contract. (Also reduces line count from 140 to 120.) See also #1048.
- [x] 3. **Remove `merkle_tree_index`**: See #1122.
- [x] 4. **Cleanups**: Consistent comment formatting, linting, more comments, etc.
- [x] 5. **Gas profiling**: Understand where gas is spent and check there is no significant wastage. See #1150.
- [x] 6. (*post-freeze discussion*) **Formal verification**: Opcode-level formal verification to start in June by [Runtime Verification](https://runtimeverification.com/).
- [x] 7. (*post-freeze discussion*) **Wait for BLS standardisation**: Various details (G1/G2 point serialisation ambiguity, cipher-suite bits, proof of possession standard, etc.) need to figured out before deployment.
- [ ] 8. (*post-freeze discussion*) **Deployment address**: Agree on mechanism to generate deployment address (e.g. use CREATE2 or not), and clearly communicate to public. (Want to avoid scam/fake deposit contracts.)
- [ ] 9. (*post-freeze discussion*) **Deploy early**: Deploy ahead of target Eth2 genesis, even if less than two clients are production ready. Suggested deposit contract deployment target: end of Q3 2019 (30 September). Suggested Eth2 genesis target: 3 January 2020 at 00:00 UTC (Bitcoin's 11'th anniversary).

**Comment by hwwhww** [comment]
Link [the formal correctness proof of `get_deposit_root` by Runtime Verification](https://github.com/runtimeverification/verified-smart-contracts/blob/master/deposit/formal-incremental-merkle-tree-algorithm.pdf) (https://github.com/ethereum/deposit_contract/issues/44#issuecomment-499625155)

Thank you @daejunpark!

**Comment by JustinDrake** [comment]
> array access for bytes[] not currently supported in vyper

We could try asking the Vyper people to add this feature :)

**Comment by djrtwo** [comment]
The pressing items here have been handled. Still need to deploy and publicize

closing

**Comment by axic** [comment]
Points 8) and 9) don't seem to have been covered here. Are there new issues for tracking them?

**Comment by q9f** [comment]
I don't think we will forget deploying the contract, so tracking it here previously just lead to confusion in the community about the potential dates. Let's see how the testnets work out before considering mainnet action items.

**Comment by JustinDrake** [comment]
> Are there new issues for tracking them?

Pinging @CarlBeek who is the deposit contract guru :)

**Comment by axic** [comment]
I specifically meant:
>  8. (post-freeze discussion) Deployment address: Agree on mechanism to generate deployment address (e.g. use CREATE2 or not), and clearly communicate to public. (Want to avoid scam/fake deposit contracts.)

Which is an important and interesting point.

**Comment by CarlBeek** [comment]
No, there currently aren't issues tracking them, but I don't necessarily think there should be.

8. I am hesitant to use `CREATE2` or at very least to define the salt ahead of time because it would allow someone to launch the "official" deposit contract ahead of time. This could lead to loss of funds if users use incorrect tooling that is not pointing to the correct address, uses the incorrect BLS standard etc. I don't see the benefit of using `CREATE2` and deploying later instead of just deploying the contract.

More generally, there is an argument to be made here that we should have a deployment procedure. These normally include constructer arguments for contract initialisation, compiler versions, and contract deployment order. The simplicity of the deposit contract means that aside from compiler version (`b13-hotfix`), these requirements are not relevant. Communicating the address with the public is the harder process and has been further complicated by the cancellation of all conferences.

9. As @q9f stated, I think it is too soon to have this discussion.
