### ISSUE TITLE
Deposit-related standardisation checklist

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#1356]
For sanity we want to standardise extra-consensus various concepts related to deposits. The suggestion is to add those standards in this repo, similar to the [networking standards](https://github.com/ethereum/eth2.0-specs/tree/dev/specs/networking). @CarlBeek is doing some experimentation in [this repo](https://github.com/CarlBeek/eth2.0-deposit-tooling).

- [x] 0. **rewrite BLS spec**: Follow new standards (see  [here](https://github.com/cfrg/draft-irtf-cfrg-hash-to-curve) and [here](https://github.com/cfrg/draft-irtf-cfrg-bls-signature)).
- [ ] 1. **checksums**: see #1183
- [ ] 2. **HD wallets**: see https://github.com/CarlBeek/eth2.0-deposit-tooling
- [ ] 3. **key store**: see https://github.com/CarlBeek/eth2.0-deposit-tooling
- [ ] 4. **quantum-secure backups**: see #1342

**Comment by vbuterin** [comment]
What's the purpose of standardizing a notion of address for validators? For transfers? In general I feel like just using the index as an ID for a validator would be best.

**Comment by djrtwo** [comment]
> What's the purpose of standardizing a notion of address for validators?

@vbuterin What are you specifically referring to?

**Comment by vbuterin** [comment]
>  1. checksums: see #1183

**Comment by vbuterin** [comment]
Why would a checksum be needed though? Checksums are there to protect against human error, and when is a human going to be putting in validator pubkey data anywhere?

**Comment by JustinDrake** [comment]
> when is a human going to be putting in validator pubkey data anywhere

For both deposits (e.g. top ups) and transfers. The reason validator indices are not ideal for transfers is that it may be possible for an attacker to manipulate them (e.g. by reordering deposits), and hence steal funds. While manipulation is hard in the context of Eth1 deposits, Eth2 deposits may be easier to reorder.

**Comment by JustinDrake** [comment]
> @JustinDrake Are you suggesting adding a checksum (beyond the root checksum) for the addr in the deposit contract?

The suggestion is to standardise on a user-/application-level checksum when manipulating validator pubkeys, especially for transfers. (No substantive change to consensus.)

**Comment by mcdee** [comment]
Not sure if this fits here or elsewhere, but there need to be checks somewhere that clients are generating correct deposit data.  Incorrect encoding of withdrawal credentials, for example, would not be picked up until someone tried to withdraw the funds by which time it would be a tad late.

The inputs to the test would be (validator private key, withdrawal private key, amount) and the output would be (deposit data root) after the signature has been applied, for example:

```
{
  "inputs": {
    "validatorkey": "1def3c44d41a17a84a678335395b484545946d1b1a56a01f3a8ea4905544e749",
    "withdrawalkey": "518b599fc3fff1dccaac87364f03575734d81ade9356a45c6fdcfd82d1b46562",
    "amount": "32000000000"
  },
  "outputs": {
    "depositdataroot": "bb96a5ace64d2b2a445b4ba860d1acece4d2cac2559d7e80d1f392717b8e6ac3"
  }
}
```

[Note we could use withdrawal public key rather than private key, but I figured it's better to provide both validator and withdrawal as private keys for consistency]

**Comment by JustinDrake** [comment]
@CarlBeek Have the items in this checklist been addressed? :)

**Comment by JustinDrake** [comment]
All the items (with the exception of checksums) have been standardised and implemented in [the default deposit interface](https://github.com/ethereum/eth2.0-deposit) (private repo for now).
