### ISSUE TITLE
Phase 0 Simplification checklist

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-specs#1435]
- [x] Remove Shards/Crosslinks from Phase 0 (#1428)
- [x] Update the networking protocol (no notation of shard subnets in phase 0, but only attestation subnets) (#1440)
- [x] Remove `Transfer` operation from Phase 0 (#1443)
